plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.3'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.diffplug.spotless' version '7.1.0'
	id 'io.qameta.allure' version '2.12.0'
	id "pl.allegro.tech.build.axion-release" version "1.19.0"
}

group = 'net.binarypaper'
version = scmVersion.version

java {
	sourceCompatibility = '21'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

springBoot {
	buildInfo {
		properties {
			additional = [
				"description": "A sample Spring Boot application to experiment Behaviour Driven Development (BDD) without any tools like Cucumber",
				"developer.name": "William Gadney",
				"developer.email": "gadnex@gmail.com",
				"license.name": "APACHE LICENSE, VERSION 2.0",
				"license.url" : "https://www.apache.org/licenses/LICENSE-2.0"
			]
		}
	}
}


repositories {
	mavenCentral()
}

ext {
	set('springModulithVersion', "1.4.1")
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.modulith:spring-modulith-starter-core'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.9'
	runtimeOnly 'com.h2database:h2'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.modulith:spring-modulith-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.modulith:spring-modulith-bom:${springModulithVersion}"
	}
}

tasks.named('processResources') {
	filesMatching('**/application.yml') {
    	expand(project.properties)
	}
}

testing {
	suites {
		bddTest(JvmTestSuite) {
			dependencies {
				implementation project()
			}
			configurations {
				bddTestImplementation {
					extendsFrom testImplementation
					extendsFrom testRuntimeOnly
				}
			}
		}
	}
}

tasks.named('bddTest') {
	jvmArgs "-javaagent:${configurations.testRuntimeClasspath.find { it.name.contains('mockito-core') }}", '-Xshare:off'
	useJUnitPlatform()
}

tasks.named('test') {
	dependsOn testing.suites.bddTest
	jvmArgs "-javaagent:${configurations.testRuntimeClasspath.find { it.name.contains('mockito-core') }}", '-Xshare:off'
	useJUnitPlatform()
}

tasks.register('bootRunDev') {
    group = 'application'
    description = 'Runs the Spring Boot application with the dev profile'
    doFirst {
        tasks.bootRun.configure {
            systemProperty('spring.profiles.active', 'dev')
        }
    }
    finalizedBy("bootRun")
}

spotless {
	java {
		googleJavaFormat()
	}
}